export {
  AccountCircle as AccountCircleIcon,
  BorderColor as BorderColorIcon,
  CheckCircle as CheckCircleIcon,
  Dashboard as DashboardIcon,
  ExpandMore as ExpandMoreIcon,
  KeyboardArrowDown as KeyboardArrowDownIcon,
  KeyboardArrowUp as KeyboardArrowUpIcon,
  Login as LoginIcon,
  Menu as MenuIcon,
  PanoramaFishEye as PanoramaFishEyeIcon,
  Search as SearchIcon,
  SwitchAccount as SwitchAccountIcon,
  Warning as WarningIcon,
} from '@mui/icons-material'
